name: ruspy

dependencies:
  - python=3.6
  - numpy=1.15.4
  - sphinx
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - matplotlib
  - pytest-cov
  - jupyter
  - numba
  - mpmath
  - pip
  - pip:
      - pyyaml
      - flake8
      - black
      - pre-commit
