name: ruspy

dependencies:
  - python
  - numpy
  - sphinx
  - pandas=1.0.0
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - matplotlib
  - pytest-cov
  - numpydoc
  - jupyter
  - numba
  - mpmath
  - pip
  - pip:
      - flake8
      - black
      - pre-commit
      - jupyter_contrib_nbextensions
      - sphinx_rtd_theme